name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 22 * * *'

jobs:
  Build-job:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x]
    name: Making Build
    steps:
      - uses: actions/checkout@v3
      - name: Install Surge
        uses: actions/setup-node@v3
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: '16.x'
      # TODO: Cache node_modules
      # https://github.com/marketplace/actions/cache
      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - run: npm install
      - run: npm run build

  Test-job:
    runs-on: ubuntu-latest
    name: Simple tests
    needs: Build-job
    if: github.ref != 'refs/head/production'
    steps:
      - uses: actions/checkout@v3
      - name: Run simple tests
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g mocha
      - run: npm run test

  Deploy-job:
    runs-on: ubuntu-latest
    # needs: [Test-job]
    name: Deploy to Surge
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      - run: npm install -g surge
      - run: surge ./public ${{secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

  Post-deploy-job:
    runs-on: ubuntu-latest
    needs: [Deploy-job]
    name: Test post-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: sudo apt install curl
      - run: curl -s -N "https://${{secrets.SURGE_DOMAIN }}" | grep "Congratulations"

  Notify-on-email:
    runs-on: ubuntu-latest
    name: EmailNotify
    needs: [Build-job, Test-job, Deploy-job, Post-deploy-job]
    if: always()
    steps:
      - uses: dawidd6/action-send-mail@v3
        name: Send mail
        with: 
          server_address: smtp.gmail.com
          server_port: 587
          # secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: ${{secrets.MAIL_ADDRESS_PRIMARY}}
          from: Mixt Media Art
          body: Workflow status of ${{github.repository}} 1) Build-job - ${{needs.Build-job.result}} 2) Test-job - ${{needs.Test-job.result}} 3) Deploy-job - ${{needs.Deploy-job.result}} 4) Post-deploy-job - ${{needs.Post-deploy-job.result}}
          # html_body: file://README.html
          priority: low


      
        
        
