name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 22 * * *'

jobs:
  Build-job:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x]
    name: Making Build
    steps:
      - uses: actions/checkout@v3
      - name: Install Surge
        uses: actions/setup-node@v3
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: '16.x'
      - run: npm install -g surge

  Test-job1:
    runs-on: ubuntu-latest
    name: Simple tests
    needs: Build-job
    if: github.ref != 'refs/head/production'
    steps:
      - uses: actions/checkout@v3
      - name: Run simple tests
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g mocha
      - run: npm test

      
        
        
